# https://taskfile.dev

version: '3'

silent: true

vars:
  CONDUCTOR_DIR: ./vagrant/conductor
  NODES_DIR: ./vagrant/nodes

includes:

  conductor:
    taskfile: ./vagrant/vagrant-taskfile.yaml
    vars:
      WORKING_DIR: "{{.CONDUCTOR_DIR}}"
      REMOVE_KEYS: false

  nodes:
    taskfile: ./vagrant/vagrant-taskfile.yaml
    vars:
      WORKING_DIR: "{{.NODES_DIR}}"
      REMOVE_KEYS: true

tasks:

  default:
    cmds:
      - task --list

  install:deps:
    desc: Install all the dependencies needed for running the project.
    cmds:
      - vagrant plugin install vagrant-list  # https://github.com/joshmcarthur/vagrant-list
      # - vagrant plugin install inifile # https://rubygems.org/gems/inifile
      # - vagrant plugin install vagrant-reload # https://github.com/aidanns/vagrant-reload/blob/master/README.md

  list:
    desc: List all the VMs initialized by Vagrant.
    cmds:
      - vagrant list

  up:
    desc: Start the conductor and nodes VMs.
    deps: [nodes:up, conductor:up]

  provision:
    desc: Provision the conductor and nodes VMs.
    deps: [nodes:provision, conductor:provision]

  destroy:
    desc: Destroy all the VMs and remove files generated by Vagrant.
    deps: [nodes:destroy, conductor:destroy]

  cleanup:
    deps: [destroy]
    desc: Destroy all the VMs and remove files generated by Vagrant.
    cmds:
      - rm -Rf ./vagrant/conductor/.vagrant
      - rm -Rf ./vagrant/nodes/.vagrant
      - echo ''
      - echo '### Cleanup done !'

  conductor:ssh:
    dir: "{{.CONDUCTOR_DIR}}"
    cmds:
      - vagrant ssh

  ansible:prepare:
    dir: "{{.CONDUCTOR_DIR}}"
    cmds:
    # https://stackoverflow.com/questions/41728722/vagrant-ssh-with-multiple-arguments
    - vagrant ssh -- -t 'cd synced_folder; ansible-playbook playbooks/00_prepare.yml'