# https://taskfile.dev

version: '3'

vars:
  CONDUCTOR_DIR: vagrant/conductor

tasks:

  up:
    cmds:
      - (cd {{.CONDUCTOR_DIR}}; vagrant up)

  ssh:
    cmds:
      - (cd {{.CONDUCTOR_DIR}}; vagrant ssh)

  provision:
    cmds:
      - (cd {{.CONDUCTOR_DIR}}; vagrant provision)

  destroy:
    cmds:
      - (cd {{.CONDUCTOR_DIR}}; vagrant destroy -f)