Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true

  config.vm.box = "debian/bullseye64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.define "conductor" do |app|
    app.vm.hostname = "conductor"
    app.vm.network "public_network", 
      ip: "172.16.0.9", 
      netmask: 16,
      bridge: ["en0: Wi-Fi (AirPort)"]
  end 
  
  config.vm.synced_folder "../../.", "/home/vagrant/project_synced_folder"
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../utilities/provision_conductor.yml"
  end

end