ansible_public_key = "id_ed25519.pub"
ansible_private_key = "id_ed25519"

Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true

  config.vm.box = "debian/bullseye64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.define "conductor" do |app|
    app.vm.hostname = "conductor"
    app.vm.network "public_network", 
      ip: "172.16.0.9", 
      netmask: 16,
      bridge: ["en0: Wi-Fi (AirPort)"]
  end 
  
  config.vm.synced_folder "../../.", "/home/vagrant/project_synced_folder"

  config.vm.provision "file", source: "~/.ssh/#{ansible_public_key}", destination: "~/.ssh/#{ansible_public_key}"
  config.vm.provision "file", source: "~/.ssh/#{ansible_private_key}", destination: "~/.ssh/#{ansible_private_key}"
  config.vm.provision "file", source: "./.add_to_bashrc", destination: "~/.add_to_bashrc"
  config.vm.provision "shell", path: "provision.sh"

end