# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

root_dir = File.dirname(File.expand_path("../."))
config = YAML.load_file("#{root_dir}/config.yml")
ansible_private_key = config['ansible_private_key']
ansible_public_key = config['ansible_public_key']
conductor_ip = config['conductor_ip']
network_bridge = config['network_bridge']
netmask = config['netmask']

Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian11"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.define "conductor" do |app|
    app.vm.hostname = "conductor"
    app.vm.network "public_network", 
      ip: conductor_ip,
      netmask: netmask,
      bridge: network_bridge
  end 
  
  config.vm.synced_folder "../../.", "/home/vagrant/synced_folder"

  config.vm.provision "file", 
    source: "./.add_to_bashrc", 
    destination: "/home/vagrant/.add_to_bashrc"
  
  config.vm.provision "file", 
    source: ansible_public_key, 
    destination: "/home/vagrant/.ssh/ansible.pub"
  
  config.vm.provision "file", 
    source: ansible_private_key, 
    destination: "/home/vagrant/.ssh/ansible"

  config.vm.provision "shell", path: "provision.sh"

end