# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

### https://stackoverflow.com/questions/16708917/how-do-i-include-variables-in-my-vagrantfile

require 'yaml'

inventory_dir = File.dirname(File.expand_path("../."))
inventory = YAML.load_file("#{inventory_dir}/inventory.yml")
test_hosts = inventory['all']['children']['test']['hosts']

Vagrant.configure("2") do |config|
  test_hosts.each do |hostname, value|
    config.vm.define hostname do |node|
      
      node.vm.box = "debian/bullseye64"
      node.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end
      
      node.vm.hostname = "#{hostname}"
      node.vm.network "public_network", 
        ip: "#{value['ansible_host']}",
        netmask: 16, 
        bridge: ["en0: Wi-Fi (AirPort)"]

      node.vm.provision "shell",
        path: "provision.sh",
        args: [
          value['provider_user'], 
          value['provider_password']
        ]
      
    end
  end
end