# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

### https://stackoverflow.com/questions/16708917/how-do-i-include-variables-in-my-vagrantfile

require 'yaml'

root_dir = File.dirname(File.expand_path("../."))

inventory = YAML.load_file("#{root_dir}/inventory.yml")
test_hosts = inventory['all']['children']['test']['hosts']

config = YAML.load_file("#{root_dir}/config.yml")
network_bridge = config['network_bridge']
netmask = config['netmask']

Vagrant.configure("2") do |config|
  test_hosts.each do |hostname, value|
    config.vm.define hostname do |node|
      
      node.vm.box = "debian/bullseye64"
      node.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end
      
      node.vm.hostname = "#{hostname}"
      node.vm.network "public_network", 
        ip: value['ansible_host'],
        netmask: netmask,
        bridge: network_bridge

      node.vm.provision "shell", inline: <<-SHELL
        sed -i 's/^PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
        # sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd
      SHELL

      node.vm.provision "shell",
        path: "provision.sh",
        args: [
          value['provider_user'], 
          value['provider_password']
        ]

      # node.vm.provision :reload
      
    end
  end
end